language: node_js
node_js:
  - "lts/*"
notifications:
  email: false
install:
  - npm ci
cache:
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache  override:
      - npm ci
    - npm run cy:verify
